/*
 This file was autogenerated with the following R routine:
 tools::package_native_routine_registration_skeleton("tensorEVD")
*/

#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* FIXME:
   Check these declarations against the C/Fortran source code.
*/

/* .Call calls */
extern SEXP R_hadamard(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP R_kronecker_cov(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP R_tensor_evd(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"R_hadamard",               (DL_FUNC) &R_hadamard,               16},
    {"R_kronecker_cov",          (DL_FUNC) &R_kronecker_cov,          12},
    {"R_tensor_evd",             (DL_FUNC) &R_tensor_evd,             13},
    {NULL, NULL, 0}
};

void R_init_tensorEVD(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
